# Generated by Django 5.0.2 on 2024-03-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_person_moneytransactions_alter_person_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='moneytransactions',
            field=models.JSONField(default=dict),
        ),
    ]
