# Generated by Django 5.0.2 on 2024-03-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_person_verified_alter_person_moneytransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bankaccounts',
            field=models.JSONField(default=dict),
        ),
    ]
