# Generated by Django 5.0.2 on 2024-03-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_person_bankaccounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='new_login',
            field=models.BooleanField(default=True),
        ),
    ]
