# Generated by Django 5.0.2 on 2024-03-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_person_new_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='currency',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='person',
            name='quote',
            field=models.TextField(default=''),
        ),
    ]
