# Generated by Django 5.0.2 on 2024-04-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_person_currency_person_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='categories',
            field=models.JSONField(default=dict),
        ),
    ]
