# Generated by Django 5.0.2 on 2024-04-28 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_person_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='categories',
            new_name='cred_category',
        ),
        migrations.AddField(
            model_name='person',
            name='dep_category',
            field=models.JSONField(default=dict),
        ),
    ]
