# Generated by Django 5.0.3 on 2024-05-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_categories_person_cred_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='adj_category',
            field=models.JSONField(default=dict),
        ),
    ]
