# Generated by Django 5.0.2 on 2024-05-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_person_adj_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='banks',
            field=models.JSONField(default=dict),
        ),
    ]
