# Generated by Django 5.0.2 on 2024-05-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_person_banks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='adj_category',
        ),
    ]
