# Generated by Django 5.0.2 on 2024-05-07 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_person_adj_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='feedback',
            field=models.JSONField(default=dict),
        ),
    ]
