# Generated by Django 5.0.2 on 2024-03-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='firstname',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='lastname',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='password',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(default='None', max_length=300),
        ),
    ]
