# Generated by Django 5.0.2 on 2024-03-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_person_firstname_person_lastname_person_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email_pin',
            field=models.IntegerField(default=0),
        ),
    ]
